TRUNCATE TABLE `sheets_base_schema.qbo_balance_sheet`;

INSERT INTO `sheets_base_schema.qbo_balance_sheet` (
  `source_relation`,
  `account_type`,
  `account_sub_type`,
  `class_id`,
  `class_name`,
  `as_of_date`,
  `calendar_date`,
  `calendar_month`,
  `calendar_year`,
  `fiscal_period`,
  `fiscal_period_date`,
  `fiscal_quarter`,
  `fiscal_year`,
  `is_first_day_of_fiscal_period`,
  `is_first_day_of_fiscal_quarter`,
  `is_first_day_of_fiscal_year`,
  `is_last_day_of_fiscal_period`,
  `is_last_day_of_fiscal_quarter`,
  `is_last_day_of_fiscal_year`,
  `amount`
)
SELECT
  `source_relation`,
  `account_type`,
  `account_sub_type`,
  `class_id`,
  `class_name`,
  `as_of_date`,
  `calendar_date`,
  `calendar_month`,
  `calendar_year`,
  `fiscal_period`,
  `fiscal_period_date`,
  `fiscal_quarter`,
  `fiscal_year`,
  `is_first_day_of_fiscal_period`,
  `is_first_day_of_fiscal_quarter`,
  `is_first_day_of_fiscal_year`,
  `is_last_day_of_fiscal_period`,
  `is_last_day_of_fiscal_quarter`,
  `is_last_day_of_fiscal_year`,
  `amount`
FROM
  `quickbooks_quickbooks.quickbooks__balance_sheet`;