-- Truncate the target table to remove existing records
TRUNCATE TABLE `sheets_base_schema.qbo_general_ledger`;

-- Insert data from the source table
INSERT INTO `sheets_base_schema.qbo_general_ledger` (
  unique_id,
  transaction_id,
  source_relation,
  transaction_index,
  transaction_date,
  customer_id,
  vendor_id,
  amount,
  account_id,
  class_id,
  department_id,
  account_number,
  account_name,
  is_sub_account,
  parent_account_number,
  parent_account_name,
  account_type,
  account_sub_type,
  financial_statement_helper,
  account_current_balance,
  account_class,
  transaction_type,
  transaction_source,
  account_transaction_type,
  created_at,
  updated_at,
  adjusted_amount,
  adjusted_converted_amount,
  running_balance,
  running_converted_balance
)
SELECT 
  unique_id,
  transaction_id,
  source_relation,
  transaction_index,
  transaction_date,
  customer_id,
  vendor_id,
  amount,
  account_id,
  class_id,
  department_id,
  account_number,
  account_name,
  is_sub_account,
  parent_account_number,
  parent_account_name,
  account_type,
  account_sub_type,
  financial_statement_helper,
  account_current_balance,
  account_class,
  transaction_type,
  transaction_source,
  account_transaction_type,
  CURRENT_TIMESTAMP() as created_at,
  CURRENT_TIMESTAMP() as updated_at,
  adjusted_amount,
  adjusted_converted_amount,
  running_balance,
  running_converted_balance
FROM `quickbooks_quickbooks.quickbooks__general_ledger`;
