-- Google Ads Ad Report table creation query
-- Contains daily performance metrics at the ad level
CREATE OR REPLACE TABLE `sheets_base_schema.google_ads_ad_report` (
  `source_relation` STRING OPTIONS(description = 'The source of the record if unioning functionality is being used'),
  `date_day` DATE OPTIONS(description = 'The date of the record'),
  `account_id` INT64 OPTIONS(description = 'The Google Ads account ID'),
  `account_name` STRING OPTIONS(description = 'The name of the Google Ads account'),
  `campaign_id` INT64 OPTIONS(description = 'The ID of the campaign'),
  `campaign_name` STRING OPTIONS(description = 'The name of the campaign'),
  `ad_group_id` STRING OPTIONS(description = 'The ID of the ad group'),
  `ad_group_name` STRING OPTIONS(description = 'The name of the ad group'),
  `ad_id` INT64 OPTIONS(description = 'The ID of the ad'),
  `ad_status` STRING OPTIONS(description = 'The status of the ad (enabled, paused, removed)'),
  `ad_type` STRING OPTIONS(description = 'The type of the ad (text, responsive search, etc.)'),
  `headline_part_1` STRING OPTIONS(description = 'First headline of the ad'),
  `headline_part_2` STRING OPTIONS(description = 'Second headline of the ad'),
  `headline_part_3` STRING OPTIONS(description = 'Third headline of the ad'),
  `description` STRING OPTIONS(description = 'Description of the ad'),
  `description_2` STRING OPTIONS(description = 'Second description of the ad'),
  `path_1` STRING OPTIONS(description = 'First part of the display URL path'),
  `path_2` STRING OPTIONS(description = 'Second part of the display URL path'),
  `impressions` INTEGER OPTIONS(description = 'Count of ad impressions'),
  `clicks` INTEGER OPTIONS(description = 'Count of ad clicks'),
  `spend` FLOAT64 OPTIONS(description = 'Spend amount in account currency'),
  `cost` NUMERIC OPTIONS(description = 'Cost of the ads in account currency'),
  `conversions` FLOAT64 OPTIONS(description = 'Count of conversions'),
  `conversions_value` FLOAT64 OPTIONS(description = 'Value of conversions'),
  `view_through_conversions` NUMERIC OPTIONS(description = 'Count of view-through conversions'),
  `ctr` NUMERIC OPTIONS(description = 'Click-through rate (clicks/impressions)'),
  `cpc` NUMERIC OPTIONS(description = 'Average cost per click'),
  `cpm` NUMERIC OPTIONS(description = 'Average cost per thousand impressions'),
  `cvr` NUMERIC OPTIONS(description = 'Conversion rate (conversions/clicks)'),
  `cpa` NUMERIC OPTIONS(description = 'Cost per acquisition (cost/conversions)'),
  `roas` NUMERIC OPTIONS(description = 'Return on ad spend (conversion_value/cost)')
)
OPTIONS (description = 'Daily performance metrics at the Google Ads ad level');