CREATE TABLE `sheets_base_schema.qbo_general_ledger` (
  `unique_id` STRING OPTIONS(description = 'Unique identifier of the general ledger line, dependent on transaction_id, transaction_index, account_id, transaction_type, transaction_source, and source_relation.'),
  `transaction_id` STRING OPTIONS(description = 'Unique identifier of the transaction. Each transaction will have an offsetting debit and credit record.'),
  `source_relation` STRING OPTIONS(description = 'The source of the record if the unioning functionality is being used. If not, this field will be null.'),
  `transaction_index` INT64 OPTIONS(description = 'Unique identifier of the individual debit and credit records of the transaction.'),
  `transaction_date` DATE OPTIONS(description = 'The date that the transaction occurred.'),
  `customer_id` STRING OPTIONS(description = 'Reference to the customer associated with the transaction.'),
  `vendor_id` STRING OPTIONS(description = 'Reference to the vendor associated with the transaction.'),
  `amount` INT64 OPTIONS(description = 'Monetary amount of the transaction line.'),
  `account_id` STRING OPTIONS(description = 'The identifier of the account associated with the transaction line.'),
  `class_id` STRING OPTIONS(description = 'Reference to the class associated with the transaction line.'),
  `department_id` STRING OPTIONS(description = 'Reference to the department with the transaction line.'),
  `account_number` STRING OPTIONS(description = 'User-defined number of the account.'),
  `account_name` STRING OPTIONS(description = 'Name of the account associated with the transaction line.'),
  `is_sub_account` BOOL OPTIONS(description = 'Boolean indicating whether the account is a sub-account (true) or a parent account (false).'),
  `parent_account_number` STRING OPTIONS(description = 'The parent account number. If the account is the parent account, then the account number is recorded.'),
  `parent_account_name` STRING OPTIONS(description = 'The parent account name. If the account is the parent account, then the account name is recorded.'),
  `account_type` STRING OPTIONS(description = 'The type of account associated with the transaction line.'),
  `account_sub_type` STRING OPTIONS(description = 'Sub-type of the account associated with the transaction line.'),
  `financial_statement_helper` STRING OPTIONS(description = 'Either "balance sheet" or "income statement" and is used to determine which financial statement the account impacts.'),
  `account_current_balance` INT64 OPTIONS(description = 'Total current balance of the account associated with the transaction line.'),
  `account_class` STRING OPTIONS(description = 'Class of the account associated with the transaction line. Will be one of "Expense", "Revenue", "Asset", "Liability", or "Equity".'),
  `transaction_type` STRING OPTIONS(description = 'Identifier of whether the transaction is a debit or credit entry.'),
  `transaction_source` STRING OPTIONS(description = 'Field signifying the source of the transaction (e.g., Bill, Invoice, Deposit, Journal Entry, etc.).'),
  `account_transaction_type` STRING OPTIONS(description = 'Identifier of whether the account is increased by either a debit or credit entry.'),
  `created_at` TIMESTAMP OPTIONS(description = 'Time at which the transaction was created.'),
  `updated_at` TIMESTAMP OPTIONS(description = 'Time at which the transaction was last updated.'),
  `adjusted_amount` INT64 OPTIONS(description = 'The amount that impacts the account. If transaction_type = account_transaction_type, then the impact increases, otherwise, it decreases the account.'),
  `adjusted_converted_amount` INT64 OPTIONS(description = 'The amount, converted with exchange rates applied if available, that impacts the account. If transaction_type = account_transaction_type, then the impact increases, otherwise, it decreases the account.'),
  `running_balance` INT64 OPTIONS(description = 'The running balance of the account by each individual day.'),
  `running_converted_balance` INT64 OPTIONS(description = 'The running balance of the account by each individual day, converted with exchange rates applied if available.')
)
OPTIONS (
  description = 'This table stores the general ledger transaction records, including account details, transaction amounts, and financial statement classifications.'
);
