-- Creates the target table for QuickBooks AP AR Enhanced with column descriptions
CREATE OR REPLACE TABLE `sheets_base_schema.qbo_ap_ar_enhanced` (
  `transaction_type` STRING OPTIONS(description = 'Set to bill if the transaction is a bill and invoice if the transaction is an invoice.'),
  `transaction_id` STRING OPTIONS(description = 'Unique identifier of the transaction for the bill or invoice.'),
  `source_relation` STRING OPTIONS(description = 'The source of the record if the unioning functionality is being used. If not this field will be null.'),
  `doc_number` STRING OPTIONS(description = 'The QuickBooks document number reference.'),
  `estimate_id` STRING OPTIONS(description = 'Unique identifier of the estimate associated with the invoice.'),
  `department_name` STRING OPTIONS(description = 'Name of the department associated with either the invoice or bill.'),
  `transaction_with` STRING OPTIONS(description = 'Set to vendor if the transaction type is a bill and customer if the transaction type is an invoice.'),
  `customer_vendor_name` STRING OPTIONS(description = 'Full name of the vendor (if a bill) or the customer (if an invoice).'),
  `customer_vendor_balance` BIGNUMERIC OPTIONS(description = 'Total current account balance of the vendor (if a bill) or the customer (if an invoice).'),
  `customer_vendor_address_city` STRING OPTIONS(description = 'City of the vendor (if a bill) or the customer (if an invoice).'),
  `customer_vendor_address_country` STRING OPTIONS(description = 'Country of the vendor (if a bill) or the customer (if an invoice).'),
  `customer_vendor_address_line` STRING OPTIONS(description = 'Address line of the vendor (if a bill) or the customer (if an invoice).'),
  `customer_vendor_website` STRING OPTIONS(description = 'The website url of the customer or vendor.'),
  `delivery_type` STRING OPTIONS(description = 'How the invoice was delivered to the customer.'),
  `estimate_status` STRING OPTIONS(description = 'The status of the invoice estimate (if applicable).'),
  `total_amount` BIGNUMERIC OPTIONS(description = 'The total monetary amount of the invoice or bill.'),
  `total_converted_amount` BIGNUMERIC OPTIONS(description = 'The total monetary converted amount, with exchange rates applied if available, of the invoice or bill.'),
  `estimate_total_amount` FLOAT64 OPTIONS(description = 'The total amount estimated of the bill or invoice (if applicable).'),
  `estimate_total_converted_amount` FLOAT64 OPTIONS(description = 'The total converted amount, with exchange rates applied if available, estimated of the bill or invoice (if applicable).'),
  `current_balance` BIGNUMERIC OPTIONS(description = 'The bill or invoice defined remaining balance of the bill or invoice.'),
  `due_date` DATE OPTIONS(description = 'The due date for the bill or invoice.'),
  `is_overdue` BOOLEAN OPTIONS(description = 'Boolean indicating whether the bill or invoice full payment is overdue.'),
  `days_overdue` BIGNUMERIC OPTIONS(description = 'The recent payment minus the due date to show the total days the total payment is overdue.'),
  `initial_payment_date` DATE OPTIONS(description = 'The first date a payment was provided for the bill or invoice'),
  `recent_payment_date` DATE OPTIONS(description = 'The last date a payment was provided for the bill or invoice.'),
  `total_current_payment` FLOAT64 OPTIONS(description = 'Sum of all total payments made towards the bill or invoice.'),
  `total_current_converted_payment` FLOAT64 OPTIONS(description = 'Sum of all total converted payments, with exchange rates applied if available, made towards the bill or invoice.'),
  `created_at` TIMESTAMP OPTIONS(description = 'The timestamp when this transaction was created.'),
  `modified_at` TIMESTAMP OPTIONS(description = 'The timestamp when this transaction was last modified.'),
  `_fivetran_synced` TIMESTAMP OPTIONS(description = 'The time when the record was last synced by Fivetran.')
)
OPTIONS (description = 'Provides the amount, amount paid, due date, and days overdue of all bills and invoices along with customer, vendor, department, and address information. This table can be used for accounts payable and accounts receivable aging analysis.'); 