-- Creates the target table for Shopify products with a limited set of columns
CREATE TABLE `sheets_base_schema.shopify_products` (
  `product_id` INT64 OPTIONS(description = 'An unsigned 64-bit integer that\'s used as a unique identifier for the product. Each id is unique across the Shopify system. No two products will have the same id, even if they\'re from different shops.'),
  `handle` STRING OPTIONS(description = 'A unique human-friendly string for the product. Automatically generated from the product\'s title.'),
  `product_type` STRING OPTIONS(description = 'A categorization for the product used for filtering and searching products.'),
  `published_scope` STRING OPTIONS(description = 'Whether the product is published to the Point of Sale channel.'),
  `title` STRING OPTIONS(description = 'The name of the product.'),
  `vendor` STRING OPTIONS(description = 'The name of the product\'s vendor.'),
  `status` STRING OPTIONS(description = 'The status of the product. Valid values: - active: The product is ready to sell and is available to customers on the online store, sales channels, and apps. By default, existing products are set to active. - archived: The product is no longer being sold and isn\'t available to customers on sales channels and apps. - draft: The product isn\'t ready to sell and is unavailable to customers on sales channels and apps. By default, duplicated and unarchived products are set to draft.'),
  `is_deleted` BOOLEAN OPTIONS(description = 'Whether the record has been deleted in the source system.'),
  `created_timestamp` TIMESTAMP OPTIONS(description = 'The date and time when the product was created.'),
  `updated_timestamp` TIMESTAMP OPTIONS(description = 'The date and time when the product was last modified.'),
  `published_timestamp` TIMESTAMP OPTIONS(description = 'The date and time (ISO 8601 format) when the product was published. Can be set to null to unpublish the product from the Online Store channel.'),
  `_fivetran_synced` TIMESTAMP OPTIONS(description = 'The time when a record was last updated by Fivetran.'),
  `source_relation` STRING OPTIONS(description = 'The schema or database this record came from, if you are unioning multiple connectors. Null if not.'),
  `collections` STRING OPTIONS(description = 'Comma-separated list of collections associated with the product.'),
  `tags` STRING OPTIONS(description = 'Comma-separated list of tags associated with the product.'),
  `count_variants` INT64 OPTIONS(description = 'Count of product variants.'),
  `has_product_image` BOOLEAN OPTIONS(description = 'If the product has an image.'),
  `total_quantity_sold` INT64 OPTIONS(description = 'Quantity of the product sold.'),
  `subtotal_sold` FLOAT64 OPTIONS(description = 'Total amount (in shop currency) of the product sold.'),
  `quantity_sold_net_refunds` FLOAT64 OPTIONS(description = 'Quantity of the product sold, excluding refunds.'),
  `subtotal_sold_net_refunds` FLOAT64 OPTIONS(description = 'Total amount (in shop currency) of the product sold, excluding refunds.'),
  `first_order_timestamp` TIMESTAMP OPTIONS(description = 'The timestamp the product was first ordered.'),
  `most_recent_order_timestamp` TIMESTAMP OPTIONS(description = 'The timestamp the product was most recently ordered.'),
  `avg_quantity_per_order_line` FLOAT64 OPTIONS(description = 'Average quantity per order line with this product.'),
  `product_total_discount` FLOAT64 OPTIONS(description = 'Total discounts associated with the product.'),
  `product_avg_discount_per_order_line` FLOAT64 OPTIONS(description = 'Average discount per order line with this product.'),
  `product_total_tax` FLOAT64 OPTIONS(description = 'Total taxes associated with the product.'),
  `product_avg_tax_per_order_line` FLOAT64 OPTIONS(description = 'Average taxes per order line with this product.')
)
OPTIONS (description = 'Contains processed product data from Shopify (limited columns).'); 
