-- Creates the target table for Shopify Line Item Enhanced with column descriptions
--NOT IN BIGQUERY--
CREATE OR REPLACE TABLE `sheets_base_schema.shopify_line_item_enhanced` (
  `header_id` INT64 OPTIONS(description = 'Id of corresponding order.'),
  `line_item_id` NUMERIC OPTIONS(description = 'Order line item id.'),
  `line_item_index` NUMERIC OPTIONS(description = 'Unique index of each line item id for each order.'),
  `record_type` STRING OPTIONS(description = 'header or line_item'),
  `created_at` TIMESTAMP OPTIONS(description = 'When the order was created'),
  `currency` STRING OPTIONS(description = 'Currency used in the order.'),
  `header_status` STRING OPTIONS(description = 'Status of the order.'),
  `product_id` NUMERIC OPTIONS(description = 'Product ID'),
  `product_name` STRING OPTIONS(description = 'Product name'),
  `transaction_type` STRING OPTIONS(description = 'Transaction type (Charge, Refund, etc)'),
  `billing_type` INT64 OPTIONS(description = 'NA for Shopify.'),
  `product_type` STRING OPTIONS(description = 'Product type'),
  `quantity` NUMERIC OPTIONS(description = 'The number of units of this line item.'),
  `unit_amount` NUMERIC OPTIONS(description = 'Amount per unit, or the price.'),
  `discount_amount` FLOAT64 OPTIONS(description = 'The discount amount associated with this order.'),
  `tax_amount` NUMERIC OPTIONS(description = 'The tax amount associated with this order.'),
  `total_amount` NUMERIC OPTIONS(description = 'Order total'),
  `payment_id` STRING OPTIONS(description = 'Transaction ID'),
  `payment_method_id` INT64 OPTIONS(description = 'Shopify does not have a particular payment_method_id, therefore all records will be null.'),
  `payment_method` STRING OPTIONS(description = 'Transaction gateway for Shopify (gift card, shopify payments, etc)'),
  `payment_at` STRING OPTIONS(description = 'Transaction processed timestamp'),
  `fee_amount` FLOAT64 OPTIONS(description = 'The total shipping fee associated with the order.'),
  `refund_amount` FLOAT64 OPTIONS(description = 'Refund amount associated with this order.'),
  `subscription_id` STRING OPTIONS(description = 'Shopify does not include subscriptions, therefore all records will be null.'),
  `subscription_plan` STRING OPTIONS(description = 'Shopify does not include subscriptions, therefore all records will be null.'),
  `subscription_period_started_at` TIMESTAMP OPTIONS(description = 'Shopify does not include subscriptions, therefore all records will be null.'),
  `subscription_period_ended_at` TIMESTAMP OPTIONS(description = 'Shopify does not include subscriptions, therefore all records will be null.'),
  `subscription_status` STRING OPTIONS(description = 'Shopify does not include subscriptions, therefore all records will be null.'),
  `customer_id` INT64 OPTIONS(description = 'Customer associated with this order.'),
  `customer_created_at` TIMESTAMP OPTIONS(description = 'The date and time when the customer was created.'),
  `customer_level` STRING OPTIONS(description = 'Whether account or customer. For Shopify, the level is customer.'),
  `customer_name` STRING OPTIONS(description = 'Customer name'),
  `customer_company` STRING OPTIONS(description = "Associated customer's company noted on the shipping address if applicable."),
  `customer_email` STRING OPTIONS(description = 'Customer email'),
  `customer_city` STRING OPTIONS(description = "Customer's shipping address city"),
  `customer_country` STRING OPTIONS(description = "Customer's shipping address country"),
  `source_relation` STRING OPTIONS(description = 'The source of the record if the unioning functionality is being used. If not this field will be empty.')
)
OPTIONS (description = 'Provides a detailed view of all order line items with enhanced information about products, customers, payments, and shipping. Useful for analyzing sales at the product level.'); 